# Generated by Django 4.0.3 on 2022-07-20 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_postmodel_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='add_date',
            field=models.DateField(default=datetime.date(2022, 7, 20), verbose_name='add date'),
        ),
    ]
