# Generated by Django 4.0.3 on 2022-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='name of user')),
                ('city', models.CharField(default=None, max_length=40, verbose_name='city')),
                ('date_of_birth', models.DateField(default=None, verbose_name='date of birth')),
                ('hobby', models.TextField(default=None, verbose_name='hobby')),
            ],
            options={
                'verbose_name': 'profile model',
                'verbose_name_plural': 'profile models',
            },
        ),
    ]
